### ISSUE TITLE
ConnectionIndex must be set in GetUsbNodeConnectionName

### ISSUE THREAD

**Issue by Anlo2846** [DerekGn/NativeUsbLib#13]
I had a problem that only USB devices connected to the root hub was enumerated. I traced it down to the method **GetUsbNodeConnectionName** where I think I have found two bugs.

The **ConnectionIndex** property of the **UsbNodeConnectionName** struct needs to be set before the **IoctlUsbGetNodeConnectionName** call. Also, the **GetUsbNodeConnectionName** method returned false when succesful and true when unsuccessful.

I made it work by making the following changes (in bold):

private static bool GetUsbNodeConnectionName(**uint portCount,** IntPtr deviceHandle,
out UsbIoControl.UsbNodeConnectionName nodeConnectionName)
:
nodeConnectionName = new UsbIoControl.UsbNodeConnectionName()
**{
  ConnectionIndex = portCount,
};**
:
if (KernelApi.DeviceIoControl(deviceHandle, UsbIoControl.IoctlUsbGetNodeConnectionName,
structPtr, bytesRequested, structPtr, bytesRequested, out _, IntPtr.Zero))
{
  nodeConnectionName =
    (UsbIoControl.UsbNodeConnectionName) Marshal.PtrToStructure(structPtr,
    typeof(UsbIoControl.UsbNodeConnectionName));

**//  return false;**
}
else
{
  Trace.TraceError(
    $"[{nameof(KernelApi.DeviceIoControl)}] [{nameof(UsbIoControl.IoctlUsbGetNodeConnectionName)}] Result: [{KernelApi.GetLastError():X}]");

  **return false;**
}

/Andreas

**Comment by DerekGn** [comment]
Thanks open a PR and I will review

**Comment by Anlo2846** [comment]
I'm still on VS2015 and had to modify your code to compile with C# 6.0, so I think it's better that you make the changes yourself.

**Comment by DerekGn** [comment]
Resolved new version 1.4.8 up on nuget https://www.nuget.org/packages/NativeUsbLib/
