### ISSUE TITLE
USB RootHubs are returning "UsbLowSpeed", instead of "UsbHighSpeed".

### ISSUE THREAD

**Issue by kseybold** [DerekGn/NativeUsbLib#17]
USB RootHubs are returning on all tested PCs "UsbLowSpeed", but in fact they are "UsbHighSpeed".

**Comment by DerekGn** [comment]
I think you need to recheck this, the code is reading the api data directly from the OS.

Change the following line
https://github.com/DerekGn/NativeUsbLib/blob/af07868735b06be6defe8729ab01794afba5835e/src/EnumerateUsb/Program.cs#L51

To

`? $"[{hub.GetDescription()}] Capabilities: [{hub.UsbHubCapabilitiesEx.CapabilityFlags}]"`

To see the hub UsbHubCapabilitiesEx flags which is a direct call and mapping from the OS.

See here

https://github.com/DerekGn/NativeUsbLib/blob/af07868735b06be6defe8729ab01794afba5835e/src/NativeUsbLib/UsbHub.cs#L134-L145

So if the hub is displayed as low speed then that is what the OS is reporting.
