### ISSUE TITLE
SuperSpeed support

### ISSUE THREAD

**Issue by taetcheson** [DerekGn/NativeUsbLib#2]
There doesn't seem to be support for detecting USB devices at SuperSpeed. Are there plans to do so?

**Comment by DerekGn** [comment]
Yes at the moment the code is as it was ported from the original repo with some bug fixes but without support for USB 3.0 devices. I was not planning any additional changes.

I can add USB 3.0 support but I will not get to it immediately as I have other stuff on my plate at the moment. At a guess it would be a week or two.

**Comment by DerekGn** [comment]
This has been resolved the new package is available from nuget.
