### ISSUE TITLE
Error loading in Framework 4.8

### ISSUE THREAD

**Issue by Gerardo-Sista** [DerekGn/NativeUsbLib#6]
Hello,
thank you for your library.
When running under framework 4.8 it raises a "Unhandled exception occurred: NativeUsbLib.Exceptions.UsbHubException: No port found!"

`ccezione generata: 'NativeUsbLib.Exceptions.UsbHubException' in NativeUsbLib.dll
CollaudoPiastra.UI.Desktop.exe Error: 0 : Unhandled exception occurred: NativeUsbLib.Exceptions.UsbHubException: No port found!
   in NativeUsbLib.UsbHub..ctor(UsbDeviceDescriptor deviceDescriptor, String devicePath)
   in NativeUsbLib.DeviceFactory.BuildDevice(Device parent, UInt32 portCount, String devicePath)
   in NativeUsbLib.UsbHub..ctor(UsbDeviceDescriptor deviceDescriptor, String devicePath)
CollaudoPiastra.UI.Desktop.exe Error: 0 : [DeviceIoControl] [IoctlUsbUserRequest] Result: [0]
CollaudoPiastra.UI.Desktop.exe Error: 0 : [DeviceIoControl] [IoctlUsbGetDescriptorFromNodeConnection] Result: [1]
CollaudoPiastra.UI.Desktop.exe Error: 0 : [DeviceIoControl] [IoctlUsbUserRequest] Result: [0]
CollaudoPiastra.UI.Desktop.exe Error: 0 : [DeviceIoControl] [IoctlUsbGetDescriptorFromNodeConnection] Result: [1]
CollaudoPiastra.UI.Desktop.exe Error: 0 : [DeviceIoControl] [IoctlUsbGetNodeConnectionName] Result: [57]
Eccezione generata: 'NativeUsbLib.Exceptions.UsbHubException' in NativeUsbLib.dll
CollaudoPiastra.UI.Desktop.exe Error: 0 : Unhandled exception occurred: NativeUsbLib.Exceptions.UsbHubException: No port found!
   in NativeUsbLib.UsbHub..ctor(UsbDeviceDescriptor deviceDescriptor, String devicePath)
   in NativeUsbLib.DeviceFactory.BuildDevice(Device parent, UInt32 portCount, String devicePath)
   in NativeUsbLib.UsbHub..ctor(UsbDeviceDescriptor deviceDescriptor, String devicePath)
Eccezione generata: 'NativeUsbLib.Exceptions.UsbControllerException' in NativeUsbLib.dll`

This happens when DLL is loading. 
Thank you for your attention.
Gerardo

**Comment by Gerardo-Sista** [comment]
Error was not in the lib. Sorry

**Comment by DerekGn** [comment]
Hey, no problem.
