### ISSUE TITLE
Question: serial port name

### ISSUE THREAD

**Issue by Gerardo-Sista** [DerekGn/NativeUsbLib#7]
Hello,
your lib is great: it is the only really working good!
I have a question:
 where can I get the serial port name the device is attached to? 
I mean "COM1", "COM2" etc. 

Thank you.

![image](https://user-images.githubusercontent.com/34858800/63252147-98123800-c26f-11e9-93c1-044db1899abc.png)

**Comment by DerekGn** [comment]
Thats the friendly name, which at the moment is not being queried by the lib. I will add it to the code and release a new version

**Comment by Gerardo-Sista** [comment]
Thank you. 
Having the port name "COM3" is extremely useful because user can select for example the peripheral from a combobox ("Prolific USB-to-Serial Comm Port") and start directly to talk to the serial port it's attached to (the com3) using the Framework's SerialPort class.
Any idea about the release time of next version?

**Comment by DerekGn** [comment]
I will release a minor patch, sometime today.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Gerardo-Sista** [comment]
Thank you very much. 
Something as a new string property like "PortName would be great".
Will wait for your fix.

Again, thank you for your great lib!!

**Comment by DerekGn** [comment]
![image](https://user-images.githubusercontent.com/4487837/63328002-390ffa00-c327-11e9-93f2-523ae937a265.png)
The new version will have the friendly name which is an attribute of some not all usb devices. You will need to check if the friendly name has a value, in your case it will, and then parse the friendly name of the device.

**Comment by Gerardo-Sista** [comment]
You're right, I checked too and, surprisingly, there's no attribute with port name only.
As you said, the  user must check if friendly name exists and parse it with a regex  "COM[0-9]+"  to get the port name. 

**SUGGESTION**
If I may suggest, I'd give it directly from your lib to the user  adding this editable property to extract the port:
NativeUsbLib.**RegexToGetTheCOM** = "COM[0-9]+"      (with this pattern by default if user doesn't set it)
Why editable? To let the user change it if Microsoft changes something (example use of [COM1] instead of (COM1) in the future).

then the user can get the port name from your lib as string: MyDeviceComPort =  device.**PortNameFromFriendlyName**

**Comment by DerekGn** [comment]
#8 

I have added the friendly name property and the ability to get the com port for a CDC device

See for an example https://github.com/DerekGn/NativeUsbLib/blob/84d2dea0bbdea048ecc6750fff0b4b7a72d4b9bb/src/EnumerateUsb/Program.cs#L84-L87

For reference you can see the USB class codes here https://www.usb.org/defined-class-codes, CDC does not however have sub codes defined so you may have a CDC device that is not a serial device in that case comport returns empty string.

I will build and push to git hub it will take an hour or two to be replicated and become public.

**Comment by Gerardo-Sista** [comment]
It works pretty well but it's not 100% reliable. 
For some USB devices like this one

![image](https://user-images.githubusercontent.com/34858800/63359855-ba8a7b00-c36d-11e9-95c8-6d7ffeb01b55.png)

even if friendly name has a COM value assigned by OS, the lib returns an empty value

![image](https://user-images.githubusercontent.com/34858800/63359768-95960800-c36d-11e9-92e6-e1d545714bac.png)

But the show must go on and for now I solved parsing the friendly name with a regex to get the port name in case your lib returns nothing.

**Thank you for the super fast support.**

**Comment by DerekGn** [comment]
Can you open the DeviceDescriptor and send me the contents

**Comment by Gerardo-Sista** [comment]
Sure, 
I am at your disposal:

![image](https://user-images.githubusercontent.com/34858800/63360847-61bbe200-c36f-11e9-940d-db96c806737a.png)

**Comment by DerekGn** [comment]
Here is what a normal CDC device reports.

![image](https://user-images.githubusercontent.com/4487837/63361793-b27c0c80-c368-11e9-8edc-bc8305b193e5.png)

This device reports its type as an interface device type =0x00 not a CDC device =0x02. More than likely its the USB interface definition that specifies CDC.

I will relax the conditional check in the ComPort property. At the moment I check the device descriptor for a CDC type. I will push this version shortly.

**Comment by Gerardo-Sista** [comment]
Derek,
I'm not so deep into device specifications.....
I have this "Prolific-USB-To-Serial Comm port" on COM3.... 
.....and getting the "COM3" name with regex (for now) makes me able to talk immediately to it.
Tha'ts all I know.
So yes, maybe you should remove any filter and simply return the com port name given by OS.

**Comment by DerekGn** [comment]
Version 1.4.6 on its way to nuget.

**Comment by Gerardo-Sista** [comment]
Thank you, 
I'll test as soon as possible with my devices and let you know.

**Comment by Gerardo-Sista** [comment]
Works perfectly. 
Thank you!
This is really a good enhancement for everyone.  :)
